### ISSUE TITLE
How to get response headers?

### ISSUE THREAD

**Issue by bslipek** [zellwk/zl-fetch#1]
Hi Zell Liew,
How can I get headers of response?
I need to `response.headers.get('Authorization ')` to get new token after each request.
In `JSONResponseHandler` we have `response.json()`, so maybe this is the problem ?
Thans in advance!

**Comment by zellwk** [comment]
@bslipek Whoops. Totally missed this issue. Sorry! 

As you suspect, the current implementation doesn't support getting response headers yet. It should be an easy fix though. Do you need still need this? 

I might be able to fix it over the weekend.

**Comment by zellwk** [comment]
@bslipek This is fixed in version 2. Check the [Quick Start section](https://github.com/zellwk/zl-fetch#quick-start) file for instructions.
