### ISSUE TITLE
Support rollup.js - duplicate export error

### ISSUE THREAD

**Issue by Buszmen** [zellwk/zl-fetch#3]
I'd like to use rollup.js module bundler, but there is a slight problem when importing the library. I get an error:

> Error: Duplicate export `zlFetch`

The problem is only with the last line in **index.js**
`module.exports.zlFetch = zlFetch`

I think this can be solved by replacing last 3 lines with that:
```js
zlFetch.zlFetch = zlFetch
module.exports = zlFetch
module.exports.default = zlFetch
```

**Comment by zellwk** [comment]
Should be fixed now. Let me know if you still get an error
