### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by saschajullmann** [zellwk/zl-fetch#5]
Hi,

I think your line in "createRequestOptions.js" where you check for window.Headers is producing an error in node v12.11.1.

If I try to run this in above mentioned node env I get the error "window is undefined".

It works as intended if you use typof window === undefined...:

"if (typeof window === 'undefined') require('isomorphic-fetch');"

**Comment by zellwk** [comment]
I pushed a fix. Try it and let me know!

**Comment by saschajullmann** [comment]
Thank you very much, that did the trick!
